name: QMK Firmware Build

on:
  push:
    paths:
      - 'Keyboards/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        uses: sekigon-gonnoc/qmk-build-action@main
        with:
          keyboard: yumiyumi17
          keymap: vial
